### ISSUE TITLE
Rails 4: NoMethodError (undefined method `read_inheritable_attribute` ...

### ISSUE THREAD

**Issue by souvik** [rails/ssl_requirement#7]
Getting this error when I am using 'ssl_requirement' with my Rails 4.0 and Ruby 2.0 application.

NoMethodError (undefined method `read_inheritable_attribute' for SessionsController:Class):
  ssl_requirement (0.1.0) lib/ssl_requirement.rb:45:in`ssl_allowed?'
  ssl_requirement (0.1.0) lib/ssl_requirement.rb:50:in `ensure_proper_protocol'
  activesupport (4.0.0) lib/active_support/callbacks.rb:407:in`_run__3063776826992777902__process_action__callbacks'
  activesupport (4.0.0) lib/active_support/callbacks.rb:80:in `run_callbacks'
  actionpack (4.0.0) lib/abstract_controller/callbacks.rb:17:in`process_action'
  actionpack (4.0.0) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (4.0.0) lib/action_controller/metal/instrumentation.rb:31:in`block in process_action'

**Comment by jai-n** [comment]
+1
I also got the same issue

**Comment by souvik** [comment]
Add below line into your Gemfile:

``` ruby
gem 'bartt-ssl_requirement', '~>1.4.0', require: 'ssl_requirement'
```

It will resolve this issue for Rails 4

**Comment by g-liu** [comment]
Confirmed working on Rails 4.1.5. This is contrary to the statement in the repo stating that gem only works for Rails 3.x versions.
